### ISSUE TITLE
Upstream syscall signatures to python-ptrace

### ISSUE THREAD

**Issue by p-e-w** [p-e-w/maybe#23]
Moving signatures to upstream where they belong could dramatically reduce clutter in `syscall_filters.py`.

**Comment by p-e-w** [comment]
The utility functions `get_syscall_register` and `get_return_value_register` should also be upstreamed.

**Comment by p-e-w** [comment]
Over the past two months, I have worked with Victor Stinner, the creator of python-ptrace, to add **all** Linux syscall signatures to python-ptrace. Today, version 0.9 of python-ptrace was released on PyPI with this and other improvements. As a result, `maybe` has lost over 100 lines of code :fireworks:

**Comment by sanketplus** [comment]
Awesome stuff @p-e-w :smiley:
