### ISSUE TITLE
What about looking into network operations as well?

### ISSUE THREAD

**Issue by IhorKravchuk** [p-e-w/maybe#27]
Would be nice to add network calls interception such as socket(), connect(), listen(), etc.

**Comment by p-e-w** [comment]
My goal is for `maybe` to block all operations that can make permanent modifications to the system. Socket calls do not fall under that category. However, I am looking into options for implementing https://github.com/p-e-w/maybe/issues/26 using a plugin architecture, which would enable network blocking via filter plugins.
