### ISSUE TITLE
bash: program: No such file or directory

### ISSUE THREAD

**Issue by Loc-Tran** [p-e-w/maybe#9]
user@user-desktop:~/Desktop$ maybe mkdir test
bash: program: No such file or directory

Not sure if it's the program or it's just an issue with my Ubuntu set up. Installed via pip.

**Comment by PenguinKenny** [comment]
Are you on 32-bit or 64-bit Ubuntu?

**Comment by clball** [comment]
To check if maybe was installed correctly and is also in your path, could you please run

`which maybe`

Ideally, it'll output the location of maybe's binary provided your path can find it:

`/usr/local/bin/maybe`

If you're not seeing that, maybe may not have installed correctly, or at least wasn't added to your path. Did you install it via pip? If so, could you run:

`pip show maybe`

That should output the installed maybe version info. If it doesn't show any info, pip doesn't have it installed. If that's the case, try installing via pip. what output do you get from running:

`sudo pip install maybe`

If you're getting something along the lines of `pip: Command not found`, you'll want to make sure you have pip and python installed. Python 2.7.11 should come bundled with pip and you can get it here: https://www.python.org/downloads/release/python-2711/

**Comment by Loc-Tran** [comment]
I am 64 bit ubuntu.

This shows up  when I use pip show maybe
---
Name: maybe
Version: 0.3.0
Location: /home/user/.local/lib/python2.7/site-packages
Requires: blessings, python-ptrace

I tried reinstalling maybe again using sudo pip install maybe and it worked. I have no idea why it's working now, thanks for the help though.

**Comment by p-e-w** [comment]
I'm closing this as the problem seems to have been solved for the OP and the original issue cannot be determined anymore.
